lsi: false
safe: true
source: /
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: Project AI101 Home
description: Pages to introduce some basic information about AI HPC
